# Generated by Django 6.1.1 on 2026-09-04 18:29

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('amount_paid', models.IntegerField()),
                ('balance', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('cost'), '-', models.F('amount_paid')), output_field=models.IntegerField())),
                ('paid_on', models.DateField(default=datetime.date.today)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='items.item')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='members.member')),
            ],
        ),
    ]
