# Generated by Django 6.1.1 on 2026-09-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cost',
            new_name='personal_contribution',
        ),
    ]
