# Generated by Django 6.1.1 on 2026-09-04 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('sub_heading', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('opening', models.TextField()),
                ('members_present', models.TextField()),
                ('members_absent', models.TextField()),
                ('agenda_approval', models.TextField()),
                ('approval_of_minutes', models.TextField()),
                ('business_from_previous_meeting', models.TextField()),
                ('new_business', models.TextField()),
                ('agenda_for_next_meeting', models.TextField()),
                ('closure', models.TextField()),
                ('minutes_submitted_by', models.CharField()),
                ('approved_by', models.CharField()),
            ],
        ),
    ]
