# Generated by Django 6.1.1 on 2026-09-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
